# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-23 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('nome', models.CharField(max_length=32)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
