# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-29 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180529_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ano', models.DateField(unique_for_year=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Aluno')),
            ],
        ),
    ]
