# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-29 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='ano',
            field=models.DateField(unique_for_date=False, unique_for_month=False, unique_for_year=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
