# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-29 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180529_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Aluno')),
            ],
        ),
        migrations.RemoveField(
            model_name='turma',
            name='aluno',
        ),
        migrations.AddField(
            model_name='turmaaluno',
            name='cod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Turma'),
        ),
    ]
